# Generated by Django 2.1.1 on 2018-09-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
